version: '3.8'

services:
  asclepius:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/asclepius
    depends_on:
      - db
    networks:
      - asclepius-network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asclepius
    networks:
      - asclepius-network

networks:
  asclepius-network:
    driver: bridge

volumes:
  postgres_data:

