version: '3.8'

services:
  asclepius:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - HEALTH_CHECK_TIME=${HEALTH_CHECK_TIME}
      - APP_PORT=${APP_PORT}
    depends_on:
      - db
    networks:
      - asclepius-network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - asclepius-network

networks:
  asclepius-network:
    driver: bridge

volumes:
  postgres_data:

