apiVersion: apps/v1
kind: Deployment
metadata:
  name: asclepius-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asclepius-service
  template:
    metadata:
      labels:
        app: asclepius-service
    spec:
      containers:
      - name: asclepius-service
        image: bluefarid/asclepius:0.0.7
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: asclepius-config
        resources:
          requests:
            cpu: "100m"  # Adjusted
            memory: "100Mi"  # Adjusted
          limits:
            cpu: "500m"  # Adjusted
            memory: "1024Mi"  # Adjusted

        startupProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 5
          failureThreshold: 5

