apiVersion: apps/v1
kind: Deployment
metadata:
  name: asclepius-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asclepius-service
  template:
    metadata:
      labels:
        app: asclepius-service
    spec:
      dnsPolicy: "None"  # Specify your own DNS settings for the pods.
      dnsConfig:
        nameservers:
          - "8.8.8.8"
          - "8.8.4.4"
          - "10.96.0.10"
        searches:
          - prod.svc.cluster.local  # This allows resolution of services within the 'prod' namespace
          - svc.cluster.local  # This allows resolution of services in any namespace
          - cluster.local  # This is for cluster level resources
          - my.dns.search.suffix
        options:
          - name: ndots
            value: "2"
          - name: edns0
      containers:
      - name: asclepius-service
        image: bluefarid/asclepius:0.0.5
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: asclepius-config
        resources:
          requests:
            cpu: "100m"  # Adjusted
            memory: "100Mi"  # Adjusted
          limits:
            cpu: "500m"  # Adjusted
            memory: "1024Mi"  # Adjusted

